<template>
  <h3 class="text-center text-white mb-3">Please Provide The Scrambles</h3>
  <form enctype="multipart/form-data" class="mx-auto shadow-lg form-holder rounded-3 px-5 pt-5" @submit.prevent="submitInfo">

    <div class="form-group py-2">
      <label for="formFile" class="form-label">
        Please provide the [comp name].json file generated by TNoodle Scrambler
        located at <b>Interchange</b> folder
      </label>
      <input class="my-3" type="file" ref="file" id="formFile" v-on:change="handleFile">
    </div>

    <input type="submit" class="btn text-white rounded-3 px-4 mt-1 mb-3" value="Submit Scrambles" />
  </form>
</template>

<script>
import { api } from '../../axios/axios-api.js'

export default {
  name: 'SubmitScramble',
  data () {
    return {
        compid: this.$route.params.id,
        formFile: null,
    }
  },
  methods: {
    handleFile (){
      this.formFile = this.$refs.file.files[0];
    },
    submitInfo(){
      let formData = new FormData();
      formData.append('ScrambleFile', this.formFile);

      api.post(`Competitions/submitScrambles/${this.compid}`,
        formData,
        {
          headers: {
            'Content-Type': 'multipart/form-data'
          }
        }
      )
        .then(res => {
          console.log(res)
          this.$router.push({ name: 'makeSchedules', params: { id: this.compid }})
        })
        .catch(err => console.log(err))
    }
  }
}
</script>

<style scoped>
.form-holder{
  background-color: #132761;
  width: 70%;
}
input:not([type=submit]):not([type=checkbox]){
  border: 1.5px solid #17b978;
  background-color: transparent;
  border-radius: 7px;
  color: #fff;
}
input[type=submit]{
  background-color: #17b978;
}
label{
  color: #fff;
}
::placeholder{
  color: #a9d1d6;
}
</style>
